#!/usr/bin/env bash
# Configures nginx on an Ubuntu server
sudo apt-get update
sudo apt-get -y nginx
sudo echo "<html><body>Hello World!</body></html>" > /var/www/html/index.html
/var/www/html/index.nginx-debian.html
sudo service nginx restart
