#!/usr/bin/env bash
#Configures an Ubuntu server; configures HAproxy
echo -e "frontend my_front\n\tmode http\n\tbind :80\n\tdefault_backend web_0s\nbackend web_0s\n\tmode http\n\tbalance roundrobin\n\tserver 494239-web-01 54.158.176.152:80 check\n\tserver 494239-web-02 54.174.67.165:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy enable
sudo service haproxy restart
