#!/usr/bin/env bash
#Configures an Ubuntu server; installs HAproxy and configures it
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9
sudo apt-get install haproxy=2.9.\*
echo -e "frontend my_front\n\tmode tcp\n\tbind :80\n\tdefault_backend web_0s\nbackend web_0s\n\tmode tcp\n\tbalance roundrobin\n\tserver 494239-web-01 54.158.176.152:80 check\n\tserver 494239-web-02 54.174.67.165:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
