#!/usr/bin/env bash
#This script does a lot of really funny things
my_pid=$$
echo "$my_pid" >>/var/run/myscript.pid
killmyself()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit
}
killmy()
{
	rm /var/run/myscript.pid
	exit
}
trap killmyself SIGTERM
trap killmyself SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT
while true; do
	echo "To infinity and beyond"
	sleep 2;
done
