#!/usr/bin/env bash
#This script does a lot of really funny things
my_pid=$$
echo "$my_pid" >>/var/run/myscript.pid
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
while true; do
	echo "To infinity and beyond"
	sleep 2;
done
