#!/usr/bin/env bash
#This script changes the loopback address of an Ubuntu server
cp /etc/hosts ~/hosts.create
sed -i 's/^127.0.0.1\s*localhost/127.0.0.2\tlocalhost/' ~/hosts.create
echo "8.8.8.8		facebook.com" >> ~/hosts.create
echo "$(cat ~/hosts.create)" > /etc/hosts
